version: '3.5'

services:
  backend:
    build: .
    container_name: help_me2
    ports:
      - 9876:9876
    environment:
      PORT: 9876
    restart: always
networks:
  default:
    name: news_network
